[build]
  functions = "functions"
  
[functions]
  included_files = ["routes/**/*.js", "controllers/**/*.js"]
  timeout = 20  # Increase if your functions are timing out (max 26 seconds)

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
